export interface QuestType {
  id: string;
  titleKey: string;
  questionKey: string;
  icon: string;
  color: string;
  overpassQuery: string;
  osmTag: string;
  elementType: "node" | "way" | "relation" | "nwr";
  answerType: "select" | "yesno" | "number" | "text" | "multi-select";
  answersSection?: string;
  answers?: { value: string; labelKey: string }[];
  category: "roads" | "buildings" | "amenities" | "accessibility";
}

export const QUEST_TYPES: QuestType[] = [
  {
    id: "surface",
    titleKey: "surface",
    questionKey: "surfaceQ",
    icon: "Route",
    color: "#4A90D9",
    overpassQuery: `way["highway"~"residential|tertiary|secondary|primary|unclassified|living_street|pedestrian|service|footway|cycleway|path|track"][!"surface"]({{bbox}});`,
    osmTag: "surface",
    elementType: "way",
    answerType: "select",
    answersSection: "surfaces",
    answers: [
      { value: "asphalt", labelKey: "asphalt" },
      { value: "concrete", labelKey: "concrete" },
      { value: "paving_stones", labelKey: "paving_stones" },
      { value: "sett", labelKey: "sett" },
      { value: "cobblestone", labelKey: "cobblestone" },
      { value: "gravel", labelKey: "gravel" },
      { value: "compacted", labelKey: "compacted" },
      { value: "fine_gravel", labelKey: "fine_gravel" },
      { value: "sand", labelKey: "sand" },
      { value: "dirt", labelKey: "dirt" },
      { value: "grass", labelKey: "grass" },
      { value: "unpaved", labelKey: "unpaved" },
      { value: "paved", labelKey: "paved" },
    ],
    category: "roads",
  },
  {
    id: "backrest",
    titleKey: "backrest",
    questionKey: "backrestQ",
    icon: "Armchair",
    color: "#8B6914",
    overpassQuery: `node["amenity"="bench"][!"backrest"]({{bbox}});`,
    osmTag: "backrest",
    elementType: "node",
    answerType: "yesno",
    category: "amenities",
  },
  {
    id: "opening_hours",
    titleKey: "openingHours",
    questionKey: "openingHoursQ",
    icon: "Clock",
    color: "#E67E22",
    overpassQuery: `nwr["shop"][!"opening_hours"]({{bbox}});nwr["amenity"~"restaurant|cafe|fast_food|bar|pub|pharmacy|bank|post_office"][!"opening_hours"]({{bbox}});`,
    osmTag: "opening_hours",
    elementType: "nwr",
    answerType: "text",
    category: "amenities",
  },
  {
    id: "wheelchair",
    titleKey: "wheelchair",
    questionKey: "wheelchairQ",
    icon: "Accessibility",
    color: "#3498DB",
    overpassQuery: `nwr["shop"][!"wheelchair"]({{bbox}});nwr["amenity"~"restaurant|cafe|fast_food|bar|pub|pharmacy|bank|post_office|hospital|clinic"][!"wheelchair"]({{bbox}});`,
    osmTag: "wheelchair",
    elementType: "nwr",
    answerType: "select",
    answersSection: "wheelchair",
    answers: [
      { value: "yes", labelKey: "yes" },
      { value: "limited", labelKey: "limited" },
      { value: "no", labelKey: "no" },
    ],
    category: "accessibility",
  },
  {
    id: "building_levels",
    titleKey: "buildingLevels",
    questionKey: "buildingLevelsQ",
    icon: "Building2",
    color: "#9B59B6",
    overpassQuery: `way["building"~"yes|residential|apartments|commercial|industrial|retail"][!"building:levels"]({{bbox}});`,
    osmTag: "building:levels",
    elementType: "way",
    answerType: "number",
    category: "buildings",
  },
  {
    id: "maxspeed",
    titleKey: "maxspeed",
    questionKey: "maxspeedQ",
    icon: "Gauge",
    color: "#E74C3C",
    overpassQuery: `way["highway"~"residential|tertiary|secondary|primary|trunk"][!"maxspeed"]({{bbox}});`,
    osmTag: "maxspeed",
    elementType: "way",
    answerType: "select",
    answers: [
      { value: "20", labelKey: "20" },
      { value: "30", labelKey: "30" },
      { value: "40", labelKey: "40" },
      { value: "50", labelKey: "50" },
      { value: "60", labelKey: "60" },
      { value: "70", labelKey: "70" },
      { value: "80", labelKey: "80" },
      { value: "90", labelKey: "90" },
      { value: "100", labelKey: "100" },
      { value: "110", labelKey: "110" },
      { value: "120", labelKey: "120" },
      { value: "130", labelKey: "130" },
    ],
    category: "roads",
  },
  {
    id: "sidewalk",
    titleKey: "sidewalk",
    questionKey: "sidewalkQ",
    icon: "Footprints",
    color: "#1ABC9C",
    overpassQuery: `way["highway"~"residential|tertiary|secondary|primary"][!"sidewalk"]({{bbox}});`,
    osmTag: "sidewalk",
    elementType: "way",
    answerType: "select",
    answersSection: "sidewalks",
    answers: [
      { value: "both", labelKey: "both" },
      { value: "left", labelKey: "left" },
      { value: "right", labelKey: "right" },
      { value: "no", labelKey: "no" },
      { value: "separate", labelKey: "separate" },
    ],
    category: "roads",
  },
  {
    id: "crossing_type",
    titleKey: "crossingType",
    questionKey: "crossingTypeQ",
    icon: "TrafficCone",
    color: "#F39C12",
    overpassQuery: `node["highway"="crossing"][!"crossing"]({{bbox}});`,
    osmTag: "crossing",
    elementType: "node",
    answerType: "select",
    answersSection: "crossings",
    answers: [
      { value: "traffic_signals", labelKey: "traffic_signals" },
      { value: "marked", labelKey: "marked" },
      { value: "uncontrolled", labelKey: "uncontrolled" },
      { value: "unmarked", labelKey: "unmarked" },
      { value: "island", labelKey: "island" },
    ],
    category: "roads",
  },
  {
    id: "building_material",
    titleKey: "buildingMaterial",
    questionKey: "buildingMaterialQ",
    icon: "Layers",
    color: "#795548",
    overpassQuery: `way["building"~"yes|residential|apartments|commercial"][!"building:material"]({{bbox}});`,
    osmTag: "building:material",
    elementType: "way",
    answerType: "select",
    answersSection: "materials",
    answers: [
      { value: "brick", labelKey: "brick" },
      { value: "stone", labelKey: "stone" },
      { value: "concrete", labelKey: "concrete" },
      { value: "wood", labelKey: "wood" },
      { value: "glass", labelKey: "glass" },
      { value: "metal", labelKey: "metal" },
      { value: "plaster", labelKey: "plaster" },
      { value: "cement_block", labelKey: "cement_block" },
    ],
    category: "buildings",
  },
  {
    id: "roof_shape",
    titleKey: "roofShape",
    questionKey: "roofShapeQ",
    icon: "Home",
    color: "#D35400",
    overpassQuery: `way["building"~"yes|residential|apartments|house|detached"][!"roof:shape"]({{bbox}});`,
    osmTag: "roof:shape",
    elementType: "way",
    answerType: "select",
    answersSection: "roofs",
    answers: [
      { value: "flat", labelKey: "flat" },
      { value: "gabled", labelKey: "gabled" },
      { value: "hipped", labelKey: "hipped" },
      { value: "pyramidal", labelKey: "pyramidal" },
      { value: "skillion", labelKey: "skillion" },
      { value: "half-hipped", labelKey: "half_hipped" },
      { value: "round", labelKey: "round" },
      { value: "gambrel", labelKey: "gambrel" },
      { value: "mansard", labelKey: "mansard" },
      { value: "dome", labelKey: "dome" },
    ],
    category: "buildings",
  },
  {
    id: "cuisine",
    titleKey: "cuisine",
    questionKey: "cuisineQ",
    icon: "UtensilsCrossed",
    color: "#C0392B",
    overpassQuery: `nwr["amenity"~"restaurant|fast_food"][!"cuisine"]({{bbox}});`,
    osmTag: "cuisine",
    elementType: "nwr",
    answerType: "select",
    answersSection: "cuisines",
    answers: [
      { value: "pizza", labelKey: "pizza" },
      { value: "burger", labelKey: "burger" },
      { value: "chinese", labelKey: "chinese" },
      { value: "japanese", labelKey: "japanese" },
      { value: "indian", labelKey: "indian" },
      { value: "thai", labelKey: "thai" },
      { value: "vietnamese", labelKey: "vietnamese" },
      { value: "mexican", labelKey: "mexican" },
      { value: "italian", labelKey: "italian" },
      { value: "french", labelKey: "french" },
      { value: "czech", labelKey: "czech" },
      { value: "kebab", labelKey: "kebab" },
      { value: "sushi", labelKey: "sushi" },
      { value: "regional", labelKey: "regional" },
      { value: "international", labelKey: "international" },
    ],
    category: "amenities",
  },
  {
    id: "internet_access",
    titleKey: "internetAccess",
    questionKey: "internetAccessQ",
    icon: "Wifi",
    color: "#2980B9",
    overpassQuery: `nwr["amenity"~"cafe|restaurant|library|coworking_space"][!"internet_access"]({{bbox}});`,
    osmTag: "internet_access",
    elementType: "nwr",
    answerType: "select",
    answersSection: "internetAccess",
    answers: [
      { value: "wlan", labelKey: "wlan" },
      { value: "wlan;fee", labelKey: "wlan_paid" },
      { value: "terminal", labelKey: "terminal" },
      { value: "no", labelKey: "no" },
    ],
    category: "amenities",
  },
  {
    id: "smoking",
    titleKey: "smoking",
    questionKey: "smokingQ",
    icon: "Wind",
    color: "#7F8C8D",
    overpassQuery: `nwr["amenity"~"restaurant|cafe|fast_food|bar|pub"][!"smoking"]({{bbox}});`,
    osmTag: "smoking",
    elementType: "nwr",
    answerType: "select",
    answersSection: "smoking",
    answers: [
      { value: "yes", labelKey: "yes" },
      { value: "no", labelKey: "no" },
      { value: "outside", labelKey: "outside" },
      { value: "separated", labelKey: "separated" },
      { value: "isolated", labelKey: "isolated" },
    ],
    category: "amenities",
  },
  {
    id: "lit",
    titleKey: "lit",
    questionKey: "litQ",
    icon: "Lightbulb",
    color: "#F1C40F",
    overpassQuery: `way["highway"~"residential|tertiary|secondary|primary|footway|cycleway|path"][!"lit"]({{bbox}});`,
    osmTag: "lit",
    elementType: "way",
    answerType: "yesno",
    category: "roads",
  },
  {
    id: "tactile_paving",
    titleKey: "tactilePaving",
    questionKey: "tactilePavingQ",
    icon: "Hand",
    color: "#16A085",
    overpassQuery: `node["highway"="crossing"][!"tactile_paving"]({{bbox}});`,
    osmTag: "tactile_paving",
    elementType: "node",
    answerType: "yesno",
    category: "accessibility",
  },
  // --- Additional quest types ---
  {
    id: "lane_count",
    titleKey: "laneCount",
    questionKey: "laneCountQ",
    icon: "ArrowLeftRight",
    color: "#5C6BC0",
    overpassQuery: `way["highway"~"tertiary|secondary|primary|trunk|motorway"][!"lanes"]({{bbox}});`,
    osmTag: "lanes",
    elementType: "way",
    answerType: "select",
    answers: [
      { value: "1", labelKey: "1" },
      { value: "2", labelKey: "2" },
      { value: "3", labelKey: "3" },
      { value: "4", labelKey: "4" },
      { value: "5", labelKey: "5" },
      { value: "6", labelKey: "6" },
    ],
    category: "roads",
  },
  {
    id: "oneway",
    titleKey: "oneway",
    questionKey: "onewayQ",
    icon: "MoveRight",
    color: "#00897B",
    overpassQuery: `way["highway"~"residential|tertiary|secondary|primary|unclassified|living_street"][!"oneway"]({{bbox}});`,
    osmTag: "oneway",
    elementType: "way",
    answerType: "yesno",
    category: "roads",
  },
  {
    id: "cycleway",
    titleKey: "cycleway",
    questionKey: "cyclewayQ",
    icon: "Bike",
    color: "#43A047",
    overpassQuery: `way["highway"~"residential|tertiary|secondary|primary"][!"cycleway"]({{bbox}});`,
    osmTag: "cycleway",
    elementType: "way",
    answerType: "select",
    answersSection: "cycleways",
    answers: [
      { value: "lane", labelKey: "lane" },
      { value: "track", labelKey: "track" },
      { value: "share_busway", labelKey: "share_busway" },
      { value: "shared_lane", labelKey: "shared_lane" },
      { value: "no", labelKey: "no" },
      { value: "separate", labelKey: "separate" },
    ],
    category: "roads",
  },
  {
    id: "handrail",
    titleKey: "handrail",
    questionKey: "handrailQ",
    icon: "Grip",
    color: "#6D4C41",
    overpassQuery: `way["highway"="steps"][!"handrail"]({{bbox}});`,
    osmTag: "handrail",
    elementType: "way",
    answerType: "yesno",
    category: "accessibility",
  },
  {
    id: "toilets_wheelchair",
    titleKey: "toiletsWheelchair",
    questionKey: "toiletsWheelchairQ",
    icon: "PersonStanding",
    color: "#0288D1",
    overpassQuery: `node["amenity"="toilets"][!"wheelchair"]({{bbox}});`,
    osmTag: "wheelchair",
    elementType: "node",
    answerType: "select",
    answersSection: "wheelchair",
    answers: [
      { value: "yes", labelKey: "yes" },
      { value: "limited", labelKey: "limited" },
      { value: "no", labelKey: "no" },
    ],
    category: "accessibility",
  },
  {
    id: "diet_vegetarian",
    titleKey: "dietVegetarian",
    questionKey: "dietVegetarianQ",
    icon: "Leaf",
    color: "#689F38",
    overpassQuery: `nwr["amenity"~"restaurant|cafe|fast_food"][!"diet:vegetarian"]({{bbox}});`,
    osmTag: "diet:vegetarian",
    elementType: "nwr",
    answerType: "select",
    answersSection: "diet",
    answers: [
      { value: "yes", labelKey: "yes" },
      { value: "only", labelKey: "only" },
      { value: "no", labelKey: "no" },
    ],
    category: "amenities",
  },
  {
    id: "outdoor_seating",
    titleKey: "outdoorSeating",
    questionKey: "outdoorSeatingQ",
    icon: "TreePine",
    color: "#2E7D32",
    overpassQuery: `nwr["amenity"~"restaurant|cafe|bar|pub"][!"outdoor_seating"]({{bbox}});`,
    osmTag: "outdoor_seating",
    elementType: "nwr",
    answerType: "yesno",
    category: "amenities",
  },
  {
    id: "fee",
    titleKey: "fee",
    questionKey: "feeQ",
    icon: "Banknote",
    color: "#FF6F00",
    overpassQuery: `node["amenity"~"parking|toilets"][!"fee"]({{bbox}});`,
    osmTag: "fee",
    elementType: "node",
    answerType: "yesno",
    category: "amenities",
  },
  {
    id: "access",
    titleKey: "access",
    questionKey: "accessQ",
    icon: "KeyRound",
    color: "#6A1B9A",
    overpassQuery: `nwr["amenity"~"parking"][!"access"]({{bbox}});`,
    osmTag: "access",
    elementType: "nwr",
    answerType: "select",
    answersSection: "access",
    answers: [
      { value: "yes", labelKey: "public" },
      { value: "customers", labelKey: "customers" },
      { value: "private", labelKey: "private" },
      { value: "permissive", labelKey: "permissive" },
    ],
    category: "amenities",
  },
  {
    id: "phone",
    titleKey: "phone",
    questionKey: "phoneQ",
    icon: "Phone",
    color: "#00796B",
    overpassQuery: `nwr["amenity"~"pharmacy|hospital|clinic|police|fire_station"][!"phone"]({{bbox}});`,
    osmTag: "phone",
    elementType: "nwr",
    answerType: "text",
    category: "amenities",
  },
  {
    id: "website",
    titleKey: "website",
    questionKey: "websiteQ",
    icon: "Globe",
    color: "#1565C0",
    overpassQuery: `nwr["shop"][!"website"][!"contact:website"]({{bbox}});`,
    osmTag: "website",
    elementType: "nwr",
    answerType: "text",
    category: "amenities",
  },
  {
    id: "capacity_bench",
    titleKey: "capacityBench",
    questionKey: "capacityBenchQ",
    icon: "Users",
    color: "#BF360C",
    overpassQuery: `node["amenity"="bench"][!"capacity"]({{bbox}});`,
    osmTag: "capacity",
    elementType: "node",
    answerType: "number",
    category: "amenities",
  },
  {
    id: "step_count",
    titleKey: "stepCount",
    questionKey: "stepCountQ",
    icon: "ArrowUp",
    color: "#4E342E",
    overpassQuery: `way["highway"="steps"][!"step_count"]({{bbox}});`,
    osmTag: "step_count",
    elementType: "way",
    answerType: "number",
    category: "accessibility",
  },
  {
    id: "shelter",
    titleKey: "shelter",
    questionKey: "shelterQ",
    icon: "Umbrella",
    color: "#0277BD",
    overpassQuery: `node["amenity"~"bus_stop|taxi"][!"shelter"]({{bbox}});`,
    osmTag: "shelter",
    elementType: "node",
    answerType: "yesno",
    category: "amenities",
  },
  {
    id: "bicycle_parking_type",
    titleKey: "bicycleParkingType",
    questionKey: "bicycleParkingTypeQ",
    icon: "Bike",
    color: "#558B2F",
    overpassQuery: `node["amenity"="bicycle_parking"][!"bicycle_parking"]({{bbox}});`,
    osmTag: "bicycle_parking",
    elementType: "node",
    answerType: "select",
    answersSection: "bikeParkingTypes",
    answers: [
      { value: "stands", labelKey: "stands" },
      { value: "wall_loops", labelKey: "wall_loops" },
      { value: "lockers", labelKey: "lockers" },
      { value: "shed", labelKey: "shed" },
      { value: "rack", labelKey: "rack" },
      { value: "ground_slots", labelKey: "ground_slots" },
    ],
    category: "amenities",
  },
];

export const QUEST_CATEGORIES = {
  roads: { icon: "Route", color: "#4A90D9" },
  buildings: { icon: "Building2", color: "#9B59B6" },
  amenities: { icon: "Store", color: "#E67E22" },
  accessibility: { icon: "Accessibility", color: "#3498DB" },
} as const;
